services:
  mongo:
    build: ./database
    image: mongo:7
    container_name: fin-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"   
    volumes:
      - mongo_data:/data/db
      - ./database/init:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_DATABASE: fin_tool

  backend:
    build: ./backend
    container_name: fin-api
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: fin_tool
      API_PORT: 3000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: fin-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      VITE_API_BASE_URL: http://localhost:8080/api
    depends_on:
      - api

  nginx:
    build: ./nginx
    container_name: fin-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend

volumes:
  mongo_data:
